CommunityProject/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CommunityProject/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CommunityProject/force-app/main/default/objects/Mail__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <description>Number of days it took for a piece of mail to be delivered.</description>
    <label>Delivery Time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CommunityProject/force-app/main/default/objects/Mail__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the piece of mail</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

CommunityProject/force-app/main/default/objects/Mail__c/fields/Tracking_ID__c.field-meta.xml
<CustomField>
    <fullName>Tracking_ID__c</fullName>
    <description>Tracking ID of an individual piece of mail</description>
    <label>Tracking ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

CommunityProject/force-app/main/default/classes/MailDummyData.cls
public class MailDummyData {

    public void mailConstruction() {
        List <Mail__c> mailList = new List <Mail__c>();
        
        for (integer i = 0; i < 25; i++) {
            Integer random = Integer.valueOf(math.random() * 135);
            Integer picklistRandom = Integer.valueOf(math.random() * 3);
            String [] picklist = new String [] {'Delivered', 'En Route', 'Missing', 'Not Shipped'};
            Mail__c newMail = new Mail__c();
            
            newMail.Tracking_ID__c = 10000 + i;
            system.debug(newMail.Tracking_ID__c);
            newMail.Name = 'Test Mail ' + random;
            newMail.Delivery_Status__c = picklist[picklistRandom];
            newMail.Price__c = math.mod(random, 2) + (picklistRandom + 1) / 10;
            
            if (picklist[picklistRandom] == 'Delivered') {
                newMail.Delivery_Time__c = Date.today();
            } else {
                newMail.Delivery_Time__c = Date.today() + 10;
            }
            
            mailList.add(newMail);
        }
        insert mailList;
    }
}